# Test your FastAPI endpoints

GET http://127.0.0.1:9032/
Accept: application/json

###

GET http://127.0.0.1:9032/hello/User
Accept: application/json

###

POST http://127.0.0.1:9032/inference
Accept: application/json
Content-Type: application/json

{
  "item": "¿Como se declara una variable en Java?"
}

###

POST http://127.0.0.1:9032/inference
Accept: application/json
Content-Type: application/json

{
  "item": "¿Como se crea una clase en Java?"
}


